#!/bin/bash
url="https://github.com/n0b0dy/gentoo-deploy-tools/archive/master.tar.gz"
gdt_path="$HOME/.gdt"
gdt_arch="gentoo-deploy-tools-master"
print_ok(){
  echo -e "\e[32m* \e[00m $1  \t \e[37m[\e[36mok\e[37m]\e[00m"
}

print_fail(){
  echo -e "\e[32m* \e[00m $1  \t \e[37m[\e[31mfail\e[37m]\e[00m"
}

if mkdir -p "$HOME/.gdt/bin" 2>&1 >/dev/null ; then
  print_ok   "Make directory\t"
else
  print_fail "Make directory\t"
fi

if wget -O- -o /dev/null $url | tar -C $gdt_path -xzf - ;then
  print_ok   "Download\t\t"
else
  print_fail "Download\t\t"
fi

if mv -f $gdt_path/$gdt_arch/bin/{gchroot,glist,gmirrors,gstrap} \
    $gdt_path/bin 2>&1 >/dev/null\
&&  mv -f $gdt_path/$gdt_arch/{gdt.rc,license,README.md} \
    $gdt_path 2>&1 >/dev/null
then
  rm -rf "${gdt_path}/${gdt_arch}"
  print_ok   "Install\t\t"
else
  print_fail "Install\t\t"
fi

source "${gdt_path}/gdt.rc"
if . $gdt_path/gdt.rc && which {gchroot,glist,gmirrors,gstrap} 2>&1 >/dev/null
then
  print_ok    "Environment variable"
else
  print_fail "Environment variable"
fi
print_ok "Install complite\t"
