#!/bin/bash
url="https://github.com/n0b0dy/gentoo-deploy-tools/archive/master.tar.gz"
gdt_path="$HOME/.gdt"
gdt_arch="gentoo-deploy-tools-master"

print_ok(){
  echo -e "\033[32m* \033[00m $1  \t \033[37m[\033[36mok\033[37m]\033[00m"
}

print_fail(){
  echo -e "\033[32m* \033[00m $1  \t \033[37m[\033[31mfail\033[37m]\033[00m"
}

if [ "$1" == "dev" ]; then    
    url="https://github.com/n0b0dy/gentoo-deploy-tools/archive/dev.tar.gz"
    gdt_arch="gentoo-deploy-tools-dev"
fi

if test -f "$HOME/.gdt/gdtrc";then
  rm -rf "$HOME/.gdt/*"  2>&1 >/dev/null
fi

if mkdir -p  "$HOME/.gdt/bin" 2>&1 >/dev/null;then
  print_ok   "Make directory\t"
else
  print_fail "Make directory\t"
fi

if wget -O- -o /dev/null $url | tar -C $gdt_path -xzf - ;then
  print_ok   "Download\t\t"
else
  print_fail "Download\t\t"
fi

if cp -rf $gdt_path/$gdt_arch/* $gdt_path/
then
  rm -rf "${gdt_path}/${gdt_arch}"
  print_ok   "Install\t\t"
else
  print_fail "Install\t\t"
fi
. $gdt_path/gdtrc
if  which {gchroot,glist,gmirrors,gstrap} 2>&1 >/dev/null
then
  print_ok    "Environment variable"
else
  print_fail "Environment variable"
fi
GDT_VERSION=$(cat $gdt_path/gdtrc | grep '^#v' | tr -d '#v')
echo -e "\033[33m» \033[00m Install complete to $gdt_path"
echo -e "\033[33m» \033[00m Version: \033[4;33m${GDT_VERSION}$(echo $gdt_arch | sed -ne 's/.*-\(dev$\)/\1/p')\033[0;00m"
unset gdt_path
unset gdt_arch
