#!/bin/sh
set -e
MIRROR_URL="www.gentoo.org/main/en/mirrors3.xml"
PROTOCOL="http\|ftp\|rsync"
SHOWN="N"

usage(){ 
  echo "Usage: ${0##*/} [options]"
  echo "Version: $VERSION"
  cat <<EOF
  -p    -protocol ftp, http, rsync
  -s    -show whithout line number 
  -h    -help

Version: 0.3.1
Licence: GNU GPL version 3 <http://www.gnu.org/licenses/gpl.html>
EOF
exit 0
}
 
mirror_list(){
mlist=$(wget -qO - $MIRROR_URL | grep '<uri' | sed -e 's/<[^>]*>//g' | sed -e 's/^\s*//g' | sed -ne "/^\($1\)/p"  | sort) 

case "$SHOWN" in
       N) echo "$mlist" | sed '/./=' | sed '/./N; s/\n/ /';;      
       *) echo "$mlist" | sed -n "$SHOWN p";; #echo "$mlist";;
      "") echo "$mlist";;
esac
}


ARGS=$(getopt -n $(basename "$0") -o 'hp:s::' -- "$@")
#[ $? = 0 ] || exit 1
eval set -- "$ARGS"

while [ "$1" != -- ]
do
    case "$1" in
       -p) PROTOCOL=$2;shift;;
       -s) SHOWN=$2; shift;;
       -h) usage;;
       --) shift;break;;
       -*) usage;;
        *) break;;            #better be the crawl directory
    esac
    shift
done
shift

mirror_list $PROTOCOL

